### ISSUE TITLE
Investigate whether `'`, `"` are legal unit names for UnitsDB symbols

### ISSUE THREAD

**Issue by opoudjis** [plurimath/asciimath2unitsml#13]

**Comment by ronaldtse** [comment]
The pair of `'` and `"` can be used for feet and inches, or used for arcminute and arcsecond.

Given that arcminute and arcsecond (the "phase angle minute" and "phase angle second") are listed in the SI Brochure as "Non-SI units accepted for use with the SI Units":
<img width="832" alt="Screenshot 2021-03-02 at 12 01 06 AM" src="https://user-images.githubusercontent.com/11865/109523502-64fa6700-7aea-11eb-88dd-801f68b97fdb.png">

Let's use `'` and `"` for "phase angle minute" and "phase angle second".

Inch and foot could be specified as `'foot` (or `apos_foot`) and `"inch` (or `quote_inch`)?

**Comment by opoudjis** [comment]
`'` is legal. `"` is presumably also legal, but seems to be breaking AsciiMath: I can't get `"unitsml(\")"` to work. (The AsciiMath parser is not that clever.)

TeX uses `'` and `''`; it has `prime` as a variant of `'`, but no `doubleprime` or `dprime` is predefined in the language.

I would be inclined to use `doubleprime` and `prime`, but I can be persuaded to use `''` and `'`'. That would make inches be `doubleprime_inch` or `''_inch`.

Let's not refer to `apos` and `quote`, since that is not what the actual symbols are.

**Comment by ronaldtse** [comment]
Then let's go with ' and ", aliased to prime and dprime.
