### ISSUE TITLE
Parsing failure on division followed by parentheses

### ISSUE THREAD

**Issue by manuelfuenmayor** [plurimath/asciimath2unitsml#26]
In SI Brochure there are *"joule per kilogram kelvin"* and *"watt per metre kelvin"* units indicated as shown below:

![Capture1](https://user-images.githubusercontent.com/33627611/112737837-e4395a00-8f33-11eb-8fa4-0c54d0fabc34.PNG)

For which, I encode:

````
stem:["unitsml(J//(kg*K),symbol:J//(kg cdot K))"]

stem:["unitsml(W//(m*K),symbol:W//(m cdot K))"]
````

And get this error:

````
MathML 500 of 1724
MathML 1000 of 1724
MathML 1500 of 1724
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rsec-1.0.0/lib/rsec/parser.rb:19:in `parse!':  (Rsec::SyntaxError)
in source:1 at 2
J//(kg*K)
  ^

....
````

**Comment by manuelfuenmayor** [comment]
Meanwhile, I'm using:

````
stem:["unitsml(J)"//("unitsml(kg*K,symbol:kg cdot K)")]


stem:["unitsml(W)"//("unitsml(m*K,symbol:m cdot K)")]
````

**Comment by opoudjis** [comment]
`J/(kg*K)` should be parsed as equivalent to `J/kg*K`, and resulting in `J*kg^-1*K^-1`.

**Comment by opoudjis** [comment]
Also, parsing (and ignoring) parentheses in unitsml expession.
