### ISSUE TITLE
Please set this gem up on GitHub Actions (and cimas)

### ISSUE THREAD

**Issue by opoudjis** [plurimath/asciimath2unitsml#4]

**Comment by CAMOBAP** [comment]
@ronaldtse could you please give me write access to push CI configuration

**Comment by opoudjis** [comment]
https://github.com/plurimath/asciimath2unitsml/pull/5 : GitHub Actions still hasn't been set up, right?

**Comment by CAMOBAP** [comment]
@opoudjis unfortunatelly(, @ronaldtse could you please give me write permissions?
