### ISSUE TITLE
add degK as notational variant of K

### ISSUE THREAD

**Issue by opoudjis** [plurimath/asciimath2unitsml#6]
... and deal with notational variants in general. Impacts unitsdb.

Also need to add rendering of units to unitsdb, such as `degC`, `render: °C`. (actually it is there in the new UnitsDB: unit_symbol)

**Comment by anermina** [comment]
Similar applies to liter - both `l` and `L` symbols should be supported.

**Comment by opoudjis** [comment]
The gem should preserve the original notation in the MathML rendering, but output the canonical unit to the UnitsML semantic annotation (including its own recommended MathML rendering.)

The notational variants are few: they should be added as `variant:` fields to UnitsDB, consisting of `symbol` and optional `render` (e.g. for `degK` = `°K`)

Division of units shall be treated as a notational variant of multiplication of inverse units: we will render `km/s`, but the UnitsML will be given for `km*s^-1`.

**Comment by opoudjis** [comment]
This has been overtaken by the new unitsdb; rendering variants are used throughout there, but have added degK.
